trigger:
- none

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Bash@3
  displayName: Veracode SCA scan
  inputs:
    targetType: 'inline'
    script: | 
      export SRCCLR_API_TOKEN="$(SRCCLR_API_TOKEN)"
      export SCAN_DIR="./app"
      curl -sSL https://download.sourceclear.com/ci.sh | bash -s scan --skip-compile --update-advisor --allow-dirty